version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
     - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
     - 6379:6379
    volumes:
      - ./redis-data:/data
