version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
     - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
     - 6379:6379
    volumes:
      - ./redis-data:/data
  api:
    build: .
    ports:
      - 4000:8080
    restart: on-failure:10
    depends_on:
      - db
      - redis
