version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
     - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
     - 6379:6379
  api:
    build: .
    ports:
      - 8080:8080
    restart: on-failure:10
    environment:
      - PORT=8080
    depends_on:
      - db
      - redis
