version: '5'

services:
  dots_api:
    tty: true
    container_name: dots_api
    hostname: dots_api
    build: ./
    environment:
     - VIRTUAL_HOST=api.dots.volt.com
     - VIRTUAL_PORT=8080
     - VIRTUAL_PORT_SSL=8443
     - HTTPS_METHOD=noredirect
    extra_hosts:
     - "api.dots.volt.com postgres.dots.volt.com"
    user: "$UID:0"
    working_dir: /go/api
    volumes:
     - ./api:go:cached
     - ~/.ssh:/tmp/.ssh
networks:
  default:
    external:
      name: dots_proxy_net
