version: '5'

services:
  dots_api:
    tty: true
    container_name: dots_api
    hostname: dots_api
    build: ./
    ports:
     - "8080:8080"
     - "8443:8443"
     - "40000:40000"  # Delve debugger port
    environment:
     - VIRTUAL_HOST=api.dots.volt.com
     - VIRTUAL_PORT=8080
     - VIRTUAL_PORT_SSL=8443
     - HTTPS_METHOD=noredirect
    extra_hosts:
      - "postgres.dots.volt.com:172.16.0.1"
    user: "$UID:0"
    working_dir: /go
    volumes:
     - ./api:/go:cached
     - ~/.ssh:/tmp/.ssh
    networks:
     - dots_proxy_net
networks:
  dots_proxy_net:
    external: true
