DROP TABLE IF EXISTS api.auth CASCADE;

DROP TABLE IF EXISTS api.company CASCADE;

DROP TABLE IF EXISTS api.deed CASCADE;

DROP TABLE IF EXISTS api.drain CASCADE;

DROP TABLE IF EXISTS api.entry CASCADE;

DROP TABLE IF EXISTS api.entry_type CASCADE;

DROP TABLE IF EXISTS api.package CASCADE;

DROP TABLE IF EXISTS api."user" CASCADE;

DROP TABLE IF EXISTS api.user_restriction CASCADE;
