DROP TABLE IF EXISTS public.auth CASCADE;

DROP TABLE IF EXISTS public.company CASCADE;

DROP TABLE IF EXISTS public.deed CASCADE;

DROP TABLE IF EXISTS public.drain CASCADE;

DROP TABLE IF EXISTS public.entry CASCADE;

DROP TABLE IF EXISTS public.entry_type CASCADE;

DROP TABLE IF EXISTS public.package CASCADE;

DROP TABLE IF EXISTS public."user" CASCADE;

DROP TABLE IF EXISTS public.user_restriction CASCADE;
